### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by zhouwenbin** [admdh/posthtml-modular-css#7]
the html file is

``` html
<css src="css/button.css">
<a href="http://best-url-ever.com" class="button">button</a>
<css src="css/box.css">
<div class="box">
    <h1>title</h1>
    <p>Some text</p>
</div>
```

output css is only button,and html file is empty

``` css
.button{
    display: block;
    height: 40px;
    line-height: 40px;
    text-align: center;
    width: 200px;
}
```

the jade example is work，but i don't want to use jade
